[fix] Handles settings breaking change from 0.5.0
Clickhouse client no longer accepts arbitrary settings with each request.

cf https://github.com/ClickHouse/clickhouse-connect/blob/main/CHANGELOG.md#warning----breaking-change----removing-get_client-arbitrary-keyword-arguments

* Retains the date_time_input_format as a general setting for all calls
* Moves old_parts_lifetime to the MergeTree table creation
  because errors are thrown if it's used by the client on non-MergeTree tables:
  clickhouse_connect.driver.exceptions.ProgrammingError: Setting old_parts_lifetime is unknown or readonly
* Ensures events table gets created with all the expected fields
* Tweaks the order_by and primary key fields for performance